language: c

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - libsqlite3-dev
      - libxml2
      - libxslt1-dev
      - uuid-dev
    update: true
  snaps:
    - name: cmake
      confinement: classic
  homebrew:
    packages:
      - libxml2
      - libxslt
      - ossp-uuid

script:
  - cmake --version | head -n1
  - mkdir build && cd build
  - cmake .. && make
