language: c

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - libsqlite3-dev
      - libxml2
      - libxslt1-dev
      - uuid-dev
  homebrew:
    packages:
      - libxml2
      - libxslt
      - ossp-uuid

install:
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="https://cmake.org/files/v3.14/cmake-3.14.7-Linux-x86_64.tar.gz"
      mkdir -p m/cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C m/cmake
      export PATH=${TRAVIS_BUILD_DIR}/m/cmake/bin:${PATH}
    fi

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make
