#!/bin/sh

conversion_test() {
    ../build/src/conversion-utility -o ${1} ${1%.xml}.sqlite3 && \
    hash=`sqlite3 -bail ${1%.xml}.sqlite3 ".sha3sum"`
    if [ -z ${hash} ]; then
        echo "${1}: test failed (unsuccessful conversion)."
        return 1
    elif [ ${hash} = ${2} ]; then
        echo "${1}: test passed."
        rm ${1%.xml}.sqlite3
        return 0
    else
        echo "${1}: test failed (hashes differ)."
        echo $hash
        return 1
    fi
}

conversion_test award-14.xml 'e9f7ae3aea05722acc642bc3ffbdc379c46bccf4d6b6b17219829d55'
conversion_test award-15.xml 'fd4406b21757b86fb147d9ced8c05506e71b13d069525b7fe687c203'
conversion_test idv-14.xml 'ece6ca14f047a7d8b46c6da1f2311ab4d88036697ac0b69985230742'
conversion_test idv-15.xml 'e0840e99b9aed0423d1fd2f1e72bd938180d200bf356ed3e38d038cf'
